# name: Playwright Tests

# on:
#   push:
#     branches:
#       - main  # Runs on push to 'main'
#   pull_request:
#     branches:
#       - main  # Runs on PRs to 'main'
#   workflow_dispatch:  # Allows manual triggering

# permissions:
#   contents: read  # Needed for actions
#   pages: write
#   id-token: write
 

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: npm install

#       - name: Install Playwright browsers
#         run: npx playwright install --with-deps

#       - name: Run Playwright tests (Headless)
#         run: npx playwright test --reporter=html

#       - name: Upload Playwright report
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: playwright-report
name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main  # Runs on push to main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test --headless --reporter=html

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

  deploy:
    name: Deploy Playwright Report to GitHub Pages
    needs: test  # Waits for the test job to finish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Playwright Report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      - name: List Downloaded Files (Debugging)
        run: ls -R playwright-report

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

