name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  actions: read
  contents: read

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install dependencies
        run: npm install

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true


      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: playwright-report

  deploy:
      name: Deploy Playwright Report to GitHub Pages
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Download Playwright Report
          uses: actions/download-artifact@v4
          with:
            name: playwright-report-${{ github.run_number }}
            path: temp-report
    
        - name: Set timestamp
          id: timestamp
          run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
    
        - name: Move report into timestamp folder
          run: |
            mkdir -p ${{ steps.timestamp.outputs.timestamp }}
            mv temp-report/* ${{ steps.timestamp.outputs.timestamp }}/
    
        - name: Generate index.html
          run: |
            echo "<html><head><title>Playwright Reports</title></head><body><h1>Test Reports</h1><ul>" > index.html
            for dir in [0-9]*/ ; do
              echo "<li><a href=\"./$dir\">$dir</a></li>" >> index.html
            done
            echo "</ul></body></html>" >> index.html

        - name: Upload timestamped reports to GitHub Pages
          uses: actions/upload-pages-artifact@v3
          with:
              path: .
    
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4
