name: Playwright Tests

on:
  push:
    branches:
      - main  # Runs on push to 'main'
  pull_request:
    branches:
      - main  # Runs on PRs to 'main'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (Headless)
        run: npx playwright test --headed=false --reporter=html

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
  deploy:
      needs: test  # Ensures deployment runs only after tests pass
      runs-on: ubuntu-latest
      steps:
        - name: Download Playwright report artifact
          uses: actions/download-artifact@v4
          with:
            name: playwright-report
            path: ./playwright-report
  
        - name: Setup GitHub Pages
          uses: actions/configure-pages@v4
  
        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v2
          with:
            path: ./playwright-report
  
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v2
