name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  actions: read
  contents: read

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Run Playwright tests
        run: npx playwright test --reporter=html
        continue-on-error: true

      - name: Generate HTML report with timestamped folder
        run: |
          mkdir -p playwright-report-${{ steps.timestamp.outputs.timestamp }}
          npx playwright show-report --output=playwright-report-${{ steps.timestamp.outputs.timestamp }}

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: playwright-report

  deploy:
    name: Deploy Playwright Report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-${{ steps.timestamp.outputs.timestamp }}
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: playwright-report-${{ steps.timestamp.outputs.timestamp }}
