name: Playwright Tests & Deploy Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

  deploy:
    name: Deploy Playwright Report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3  
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
